Repository slow-and-serious/caller-app, pull requests merged in 2020-10, with the labels that each got.

#11 readme updated, build removed from gitignore
  .gitignore
  README.md
  docs/assets/ERD_mockup.png
  docs/assets/areas_of_expertise.png
  docs/assets/wireframes.png
  docs/requirements.md
  frontend/build/asset-manifest.json
  frontend/build/favicon.ico
  frontend/build/index.html
  frontend/build/logo192.png
  frontend/build/logo512.png
  frontend/build/manifest.json
  frontend/build/precache-manifest.e0388413f2029edf00c17725b6133d88.js
  frontend/build/robots.txt
  frontend/build/service-worker.js
  frontend/build/static/css/main.dc0a14bb.chunk.css
  frontend/build/static/css/main.dc0a14bb.chunk.css.map
  frontend/build/static/js/2.866d80c2.chunk.js
  frontend/build/static/js/2.866d80c2.chunk.js.LICENSE.txt
  frontend/build/static/js/2.866d80c2.chunk.js.map
  frontend/build/static/js/main.a680be93.chunk.js
  frontend/build/static/js/main.a680be93.chunk.js.map
  frontend/build/static/js/runtime-main.c8a21426.js
  frontend/build/static/js/runtime-main.c8a21426.js.map
Labels: documentation

#15 fixed bug on posting in DRF
  notifications/models.py
  notifications/serializers.py
Labels: bug

#20 Models and 2 fa
  README.md
  docs/assets/qr_admin.png
  docs/assets/qr_manager.png
  notifications/migrations/0002_auto_20201029_0241.py
  notifications/urls.py
  poetry.lock
  pyproject.toml
  server/settings.py
  server/urls.py
  users/admin.py
  users/forms.py
Labels: enhancement

#27 User profile
  README.md
  frontend/build/precache-manifest.e84b853a1f374540ebf83fa741175ef0.js
  frontend/build/static/js/main.e083014f.chunk.js
  frontend/build/static/js/main.e083014f.chunk.js.map
  frontend/package-lock.json
  frontend/src/App.js
  frontend/src/components/Login.js
  frontend/src/components/Logout.js
  frontend/src/components/Table.js
  frontend/src/index.js
  frontend/src/services/axios.js
  notifications/admin.py
  notifications/migrations/0003_auto_20201029_2348.py
  notifications/migrations/0004_notification_rotation.py
  notifications/models.py
  notifications/serializers.py
  notifications/urls.py
  notifications/views.py
  poetry.lock
  pyproject.toml
  server/settings.py
  server/urls.py
  twilioHandler/urls.py
  users/admin.py
  users/apps.py
  users/migrations/0003_profile.py
  users/migrations/0004_auto_20201029_1902.py
  users/migrations/0005_profile_manager.py
  users/models.py
  users/permissions.py
  users/serializers.py
  users/signals.py
  users/urls.py
  users/views.py
Labels: enhancement

#28 wired up the calling logic, still sync NOT async
  notifications/migrations/0005_notification_completed.py
  notifications/models.py
  notifications/views.py
  server/urls.py
  twilioHandler/twilio/example.py
  twilioHandler/twilio/notification_orchestrator.py
  twilioHandler/urls.py
  twilioHandler/views.py
Labels: enhancement

#30 Table
  frontend/package-lock.json
  frontend/src/components/Table.js
  package.json
  yarn.lock
Labels: enhancement

#32 Api routes
  README.md
  notifications/migrations/0006_auto_20201030_1922.py
  notifications/models.py
  notifications/serializers.py
  notifications/urls.py
  notifications/views.py
  poetry.lock
  pyproject.toml
Labels: enhancement
