Repository slow-and-serious/caller-app, pull requests merged in 2020-11, with the labels that each got.

#42 Bugfix
  frontend/src/components/Login.js
  frontend/src/components/StartRotation.js
  notifications/serializers.py
  notifications/views.py
  server/urls.py
  twilioHandler/twilio/example.py
  twilioHandler/twilio/notification_orchestrator.py
  twilioHandler/views.py
Labels: bugfix

#41 Fix profile
  frontend/build/asset-manifest.json
  frontend/build/index.html
  frontend/build/precache-manifest.0634b29e7cf88dcfe62bfe2f3dde1e2c.js
  frontend/build/precache-manifest.53fdf1de0015e6fdfe390bc19f44bf23.js
  frontend/build/service-worker.js
  frontend/build/static/js/2.28818fef.chunk.js
  frontend/build/static/js/2.28818fef.chunk.js.LICENSE.txt
  frontend/build/static/js/2.28818fef.chunk.js.map
  frontend/build/static/js/2.800ba773.chunk.js
  frontend/build/static/js/2.800ba773.chunk.js.map
  frontend/build/static/js/main.076f83ca.chunk.js
  frontend/build/static/js/main.076f83ca.chunk.js.map
  frontend/build/static/js/main.2ea1d79a.chunk.js
  frontend/build/static/js/main.2ea1d79a.chunk.js.map
  frontend/build/static/js/main.fe56df3b.chunk.js
  frontend/build/static/js/main.fe56df3b.chunk.js.map
  frontend/build/static/js/runtime-main.c8a21426.js
  frontend/build/static/js/runtime-main.c8a21426.js.map
  frontend/src/App.js
  frontend/src/components/Header.js
  frontend/src/components/Login.js
Labels: enhancement

#50 Cleaning up
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/About.js
  frontend/src/components/Body.js
  frontend/src/components/BodyLayout.js
  frontend/src/components/Green.css
  frontend/src/components/Green.js
  frontend/src/components/Header.js
  frontend/src/components/HowItWorks.js
  frontend/src/components/Landing.js
  frontend/src/components/Login.js
  frontend/src/components/Notifications.js
  frontend/src/components/Profile.js
  frontend/src/components/Rotation.js
  frontend/src/components/RotationDetail.js
  frontend/src/components/StartRotation.js
  frontend/src/components/Table.js
  frontend/yarn.lock
  notifications/serializers.py
Labels: bugfix, enhancement

#52 Cleaning up
  README.md
  docs/assets/ERD.png
  frontend/src/App.js
  frontend/src/components/BodyLayout.js
  frontend/src/components/Notifications.js
  frontend/src/components/Profile.js
  frontend/src/components/Table.js
  notifications/views.py
  poetry.lock
  pyproject.toml
  requirements.txt
  server/settings.py
Labels: bugfix, documentation
